# Hologram position settings
hologram:
  # Base height is Entity center height
  height-offset: 0.4

  # Delay in ticks
  remove-after-ticks: 40
  lines:
    - "%type%"
    - "%damage%"

messages:
  hit: "&6âš” Hit"
  critical: "&cğŸ’¥ CRIT"
  trident: "&bğŸ”± Trident"
  damage: "&4â¤ %damage%"
